import { NextRequest, NextResponse } from 'next/server'
import { supabaseAdmin } from '@/lib/supabase'

export const dynamic = 'force-dynamic'

const GH_API = 'https://api.github.com'
const WORKFLOW_FILE = '.github/workflows/wb-apply.yml'
const MANAGE_URL = 'https://manage.worker-bee.app'

function workflowYaml(siteId: string): string {
  return `name: "Worker Bee — Apply Blueprint"

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Blueprint branch name"
        required: true
      site_id:
        description: "Worker Bee site ID"
        required: true
        default: "${siteId}"

jobs:
  apply:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Claude Code CLI
        run: npm install -g @anthropic-ai/claude-code@latest

      - name: Fetch wb-apply script
        run: curl -fsSL ${MANAGE_URL}/api/scripts/wb-apply -o wb-apply.mjs

      - name: Apply blueprint patches
        env:
          ANTHROPIC_API_KEY: \${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          node wb-apply.mjs \\
            --site "\${{ inputs.site_id }}" \\
            --branch "\${{ inputs.branch }}" \\
            --dir .

      - name: Open pull request
        uses: peter-evans/create-pull-request@v7
        with:
          token: \${{ secrets.GITHUB_TOKEN }}
          commit-message: "fix: apply Worker Bee blueprint \${{ inputs.branch }}"
          branch: "wb/\${{ inputs.branch }}"
          delete-branch: true
          title: "🐝 Worker Bee: \${{ inputs.branch }}"
          body: |
            ## Worker Bee — Automated Fix Blueprint

            Applied blueprint branch \`\${{ inputs.branch }}\` from [manage.worker-bee.app](${MANAGE_URL}/sites/\${{ inputs.site_id }}/blueprint).

            ### What to do
            1. Check the **Vercel preview URL** posted above by the Vercel bot
            2. Click through the live preview on desktop + mobile
            3. If everything looks good → **merge** — Vercel deploys automatically
            4. If you want changes → comment on this PR or trigger another apply run

            ---
            > Generated by [Worker Bee](${MANAGE_URL}) · [View blueprint](${MANAGE_URL}/sites/\${{ inputs.site_id }}/blueprint)
          labels: |
            worker-bee
            automated
`
}

function ghHeaders(token: string): HeadersInit {
  return {
    Authorization: `Bearer ${token}`,
    Accept: 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
    'Content-Type': 'application/json',
  }
}

export async function POST(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  const { branch } = (await req.json()) as { branch: string }

  if (!branch) return NextResponse.json({ error: 'branch required' }, { status: 400 })

  const { data: raw } = await supabaseAdmin.from('sites').select('*').eq('id', id).single()
  if (!raw) return NextResponse.json({ error: 'Site not found' }, { status: 404 })

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const site = raw as any
  const repo: string | null = site.github_repo
  if (!repo) {
    return NextResponse.json({ error: 'No GitHub repo configured on this site. Add it in site settings.' }, { status: 400 })
  }

  const token = process.env.GITHUB_TOKEN
  if (!token) {
    return NextResponse.json({ error: 'GITHUB_TOKEN not configured on the server.' }, { status: 500 })
  }

  const headers = ghHeaders(token)

  // ── 1. Check if workflow exists; install if not ─────────────────────────
  const checkRes = await fetch(`${GH_API}/repos/${repo}/contents/${encodeURIComponent(WORKFLOW_FILE)}`, { headers })
  let workflowInstalled = false

  if (!checkRes.ok) {
    const yaml = workflowYaml(id)
    const installRes = await fetch(`${GH_API}/repos/${repo}/contents/${encodeURIComponent(WORKFLOW_FILE)}`, {
      method: 'PUT',
      headers,
      body: JSON.stringify({
        message: 'chore: add Worker Bee apply workflow',
        content: Buffer.from(yaml).toString('base64'),
      }),
    })
    if (!installRes.ok) {
      const err = await installRes.json().catch(() => ({}))
      return NextResponse.json(
        { error: `Could not install workflow: ${(err as { message?: string }).message ?? installRes.status}` },
        { status: 500 },
      )
    }
    workflowInstalled = true
    // Let GitHub register the new workflow before dispatching
    await new Promise(r => setTimeout(r, 3000))
  }

  // ── 2. Trigger workflow_dispatch ────────────────────────────────────────
  const dispatchRes = await fetch(`${GH_API}/repos/${repo}/actions/workflows/wb-apply.yml/dispatches`, {
    method: 'POST',
    headers,
    body: JSON.stringify({
      ref: 'main',
      inputs: { branch, site_id: id },
    }),
  })

  // 204 = success, no body
  if (!dispatchRes.ok && dispatchRes.status !== 204) {
    const err = await dispatchRes.json().catch(() => ({}))
    return NextResponse.json(
      { error: `GitHub dispatch failed: ${(err as { message?: string }).message ?? dispatchRes.status}` },
      { status: 500 },
    )
  }

  return NextResponse.json({
    dispatched: true,
    workflowInstalled,
    repo,
    actionsUrl: `https://github.com/${repo}/actions/workflows/wb-apply.yml`,
    pullsUrl: `https://github.com/${repo}/pulls`,
  })
}
